### ISSUE TITLE
Not Compiling on XCode 12.x.x SIMULATOR (was ok on XCode 11.7 Simulator)

### ISSUE THREAD

**Issue by vassily-fr** [hipay/hipay-fullservice-sdk-ios#93]
Hi, 

The SDK is not compiling on the new XCode

Here is the error : 
`ld: in /Users/xxxxx/ProjetsGit/Projects/MyProject/Pods/HiPayFullservice/HiPayFullservice/Payment Screen/CardIO/libCardIO.a(CardIOCardholderNameTextFieldDelegate.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/xxxxxx/ProjetsGit/Projects/MyProject/Pods/HiPayFullservice/HiPayFullservice/Payment Screen/CardIO/libCardIO.a' for architecture arm64
`

It compiles also fine on Real devices

Is there a way to fix this ?

Thanks

**Comment by frankois941** [comment]
hey, 
@vassily-fr 
you should add on your podfile these lines:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # Fixing a bug on Xcode 12
        # some pods when using simulator, build for arm64 and the linking failed
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      end
  end
end
```

**Comment by morganHipay** [comment]
Hello,
We fix the problem by removing Card.IO library in the latest release [2.0.0](https://github.com/hipay/hipay-fullservice-sdk-ios/releases/tag/2.0.0) because the library is no longer supported.

If you really want to include it, you have to choose the [Advanced Integration](https://developer.hipay.com/mobile-payments/ios/ios-advanced-integration) and create a scan card button in your custom payment screen.
